name: suggest
description: Suggest is a food and disease reference app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+2

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.5"
  flutter_localizations:
    sdk: flutter
  cached_network_image: "3.2.3"
  # flutter_html: "2.0.0"
  get: "4.6.5"
  get_storage: "2.1.1"
#  flutter_radar_chart: "0.2.1"
#  http: "0.13.5"
  google_fonts:
  intl: "0.17.0"
  shared_preferences: "2.1.0"
#  webview_flutter: "2.8.0"
  url_launcher: "6.1.10"

dev_dependencies:
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: "0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: "2.0.1"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/diseases/
    - assets/fonts/  
    - assets/jsons/
    - assets/nutritions/
    - assets/sellers/
    - assets/unhealthy/    
    - assets/vegs/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
        

#module:
#  androidX: true


flutter_native_splash:
  background_image: assets/back.png
  image: assets/suggest.png
  ios: false
  web: false
  branding: assets/scenac.png
  branding_mode: bottom
  fullscreen: true